// 타입 import만 — 런타임 의존성 없음
export const mockDigest = {
  weather: "LLM 가격 경쟁이 치열해지고, 오픈소스 멀티모달 모델이 급부상하는 하루.",
  topicTrends: { LLM: 9, Vision: 6, Agent: 7, OpenSource: 8, Regulation: 3, Hardware: 5 },
  news: [
    { title: "OpenAI, GPT-5 공개 임박 — 멀티모달 추론 성능 대폭 개선", summary: "OpenAI가 차세대 모델 GPT-5의 출시를 앞두고 있다. 멀티모달 추론에서 기존 대비 40% 성능 향상이 예상되며, 코드 생성과 수학 문제 해결 능력이 크게 강화되었다.", url: "https://example.com/1", source: "TechCrunch AI" },
    { title: "Anthropic, Claude 4.5 Opus 업데이트 — 코드 에이전트 성능 1위", summary: "Anthropic이 Claude 4.5 Opus를 업데이트했다. SWE-bench에서 최고 점수를 기록하며, 자율 코딩 에이전트 분야에서 GPT-4를 앞섰다.", url: "https://example.com/2", source: "The Verge AI" },
    { title: "Meta, Llama 4 Scout 오픈소스 공개 — 1000만 토큰 컨텍스트", summary: "Meta가 Llama 4 Scout를 오픈소스로 공개했다. 1000만 토큰의 컨텍스트 윈도우를 지원하며, 16개의 전문가 모듈을 사용하는 MoE 아키텍처를 채택했다.", url: "https://example.com/3", source: "MIT Tech Review" },
    { title: "Google DeepMind, Gemini 2.5 Pro 실험 버전 공개", summary: "Google이 Gemini 2.5 Pro 실험 버전을 공개했다. 추론 능력이 대폭 강화되었으며, 코드 생성 벤치마크에서 업계 최고 수준을 달성했다.", url: "https://example.com/4", source: "Google AI Blog" },
    { title: "NVIDIA H200 칩 양산 시작 — AI 학습 속도 2배", summary: "NVIDIA가 H200 GPU의 양산을 시작했다. H100 대비 메모리 대역폭이 2배로 늘어나 대규모 모델 학습 시간을 크게 단축할 수 있다.", url: "https://example.com/5", source: "NVIDIA AI" },
    { title: "Mistral, Codestral Mamba 출시 — 경량 코딩 모델", summary: "Mistral이 코드 특화 모델 Codestral Mamba를 출시했다. 파라미터 수 대비 뛰어난 코드 생성 성능을 보여주며, 로컬 환경에서도 구동 가능하다.", url: "https://example.com/6", source: "Hugging Face" },
    { title: "EU AI Act 시행 6개월 — 기업들의 대응 현황", summary: "EU AI Act 시행 6개월이 지났다. 주요 AI 기업들이 투명성 보고서를 제출하기 시작했으며, 고위험 AI 시스템 분류 기준이 구체화되고 있다.", url: "https://example.com/7", source: "Ars Technica" },
    { title: "Cursor, AI 코딩 에디터 1.0 정식 출시", summary: "AI 코딩 에디터 Cursor가 1.0 정식 버전을 출시했다. VS Code 기반에서 독자 에디터로 전환하며, 에이전트 모드에서 자율 코딩이 가능해졌다.", url: "https://example.com/8", source: "VentureBeat AI" },
    { title: "DeepSeek-V3, 오픈소스 LLM 벤치마크 1위 달성", summary: "중국 AI 스타트업 DeepSeek이 V3 모델로 오픈소스 LLM 벤치마크 1위를 달성했다. Llama 4와 경쟁하며 중국 AI의 기술력을 입증했다.", url: "https://example.com/9", source: "AI News" },
    { title: "Microsoft, Azure AI에 실시간 음성 API 추가", summary: "Microsoft가 Azure AI 서비스에 실시간 음성 변환 API를 추가했다. GPT-4o의 음성 기능을 API로 제공하며, 고객 서비스 자동화에 활용 가능하다.", url: "https://example.com/10", source: "Microsoft AI" },
  ],
  community: [
    { title: "Claude Code로 풀스택 앱 24시간 만에 만든 후기", summary: "개발자가 Claude Code를 사용해 풀스택 앱을 24시간 만에 완성한 경험을 공유했다. 프롬프트 전략과 에이전트 모드 활용법이 화제다.", url: "https://example.com/c1", source: "Hacker News", upvotes: 482, comments: 156 },
    { title: "LLM을 프로덕션에 배포할 때 실수하는 10가지", summary: "시니어 ML 엔지니어가 LLM 프로덕션 배포 시 흔한 실수를 정리했다. 토큰 비용 관리, 할루시네이션 방지, 레이턴시 최적화 등 실전 팁이 포함되어 있다.", url: "https://example.com/c2", source: "Lobsters", upvotes: 234, comments: 89 },
    { title: "RAG는 죽었다? — 파인튜닝 vs RAG 최신 비교", summary: "RAG와 파인튜닝의 최신 성능을 비교한 글이 커뮤니티에서 뜨거운 토론을 불러일으켰다. 유즈케이스별 최적 접근법이 다르다는 결론.", url: "https://example.com/c3", source: "DEV.to", upvotes: 178, comments: 67 },
    { title: "vLLM vs TGI vs Ollama — 로컬 추론 엔진 벤치마크 2026", summary: "주요 로컬 추론 엔진 3종의 최신 벤치마크 결과. vLLM이 처리량에서 앞서고, Ollama가 설치 편의성에서 우위를 보였다.", url: "https://example.com/c4", source: "Hacker News", upvotes: 312, comments: 98 },
    { title: "AI Agent가 코드 리뷰를 대체할 수 있을까?", summary: "AI 에이전트를 코드 리뷰에 도입한 팀의 6개월 후기. 단순 버그는 잘 잡지만 아키텍처 리뷰는 아직 사람이 필요하다는 결론.", url: "https://example.com/c5", source: "Lobsters", upvotes: 156, comments: 72 },
    { title: "프롬프트 엔지니어링은 끝났다 — 에이전트 엔지니어링의 시대", summary: "프롬프트 엔지니어링에서 에이전트 엔지니어링으로 패러다임이 전환되고 있다는 분석글. 도구 사용, 메모리, 계획 수립이 핵심.", url: "https://example.com/c6", source: "Hacker News", upvotes: 445, comments: 201 },
    { title: "Tailwind v4 + AI — 디자인 시스템 자동 생성기 만들기", summary: "Tailwind v4와 AI를 결합해 디자인 시스템을 자동 생성하는 도구를 만든 개발자의 튜토리얼.", url: "https://example.com/c7", source: "DEV.to", upvotes: 89, comments: 23 },
    { title: "GPU 가난한 개발자를 위한 양자화 가이드 2026", summary: "4bit, 8bit 양자화부터 GGUF 포맷까지, 제한된 GPU 메모리로 LLM을 돌리는 실전 가이드. M4 Mac에서의 성능 측정도 포함.", url: "https://example.com/c8", source: "Hacker News", upvotes: 267, comments: 84 },
    { title: "Next.js + Vercel AI SDK로 챗봇 만들기 완전 가이드", summary: "Vercel AI SDK를 사용한 스트리밍 챗봇 구현 튜토리얼. Claude, GPT-4 등 다양한 모델을 플러그인 방식으로 교체할 수 있다.", url: "https://example.com/c9", source: "DEV.to", upvotes: 134, comments: 41 },
    { title: "2026년 ML 엔지니어 연봉 서베이 결과", summary: "전 세계 5000명의 ML 엔지니어를 대상으로 한 연봉 조사 결과. 시니어 ML 엔지니어의 평균 연봉이 전년 대비 15% 상승했다.", url: "https://example.com/c10", source: "Hacker News", upvotes: 523, comments: 312 },
  ],
  github: [
    { name: "anthropics/claude-code", description: "Anthropic의 공식 CLI 기반 AI 코딩 에이전트. 터미널에서 자연어로 코드를 작성, 수정, 디버깅할 수 있다.", url: "https://github.com/anthropics/claude-code", stars: 28500, todayStars: 450, language: "TypeScript" },
    { name: "microsoft/VibeVoice", description: "Microsoft의 실시간 음성 변환 도구. AI 모델을 활용해 텍스트를 자연스러운 음성으로 변환한다.", url: "https://github.com/microsoft/VibeVoice", stars: 8200, todayStars: 380, language: "Python" },
    { name: "NousResearch/hermes-agent", description: "자율 AI 에이전트 프레임워크. 도구 사용, 메모리 관리, 멀티스텝 추론을 지원한다.", url: "https://github.com/NousResearch/hermes-agent", stars: 5600, todayStars: 290, language: "Python" },
    { name: "vllm-project/vllm", description: "고성능 LLM 추론 엔진. PagedAttention으로 메모리를 효율적으로 관리하며, 처리량이 뛰어나다.", url: "https://github.com/vllm-project/vllm", stars: 42000, todayStars: 210, language: "Python" },
    { name: "langchain-ai/langgraph", description: "LangChain의 에이전트 오케스트레이션 프레임워크. 상태 기반 그래프로 복잡한 AI 워크플로를 설계한다.", url: "https://github.com/langchain-ai/langgraph", stars: 15800, todayStars: 180, language: "Python" },
    { name: "huggingface/smolagents", description: "Hugging Face의 경량 AI 에이전트 라이브러리. 코드 기반 액션으로 도구를 호출하며 간단하게 에이전트를 구축한다.", url: "https://github.com/huggingface/smolagents", stars: 9300, todayStars: 165, language: "Python" },
    { name: "ollama/ollama", description: "로컬에서 LLM을 실행하는 가장 쉬운 도구. Docker처럼 모델을 pull하고 run하면 된다.", url: "https://github.com/ollama/ollama", stars: 118000, todayStars: 150, language: "Go" },
    { name: "open-webui/open-webui", description: "ChatGPT 스타일의 셀프 호스팅 웹 UI. Ollama와 연동해 로컬 모델을 브라우저에서 사용한다.", url: "https://github.com/open-webui/open-webui", stars: 78000, todayStars: 140, language: "TypeScript" },
    { name: "browser-use/browser-use", description: "AI가 실제 웹 브라우저를 조작하는 에이전트. 웹 자동화, 데이터 수집, 테스트에 활용된다.", url: "https://github.com/browser-use/browser-use", stars: 21000, todayStars: 130, language: "Python" },
    { name: "astral-sh/uv", description: "Rust로 만든 초고속 Python 패키지 관리자. pip 대비 10-100배 빠르며, 가상환경 관리도 지원한다.", url: "https://github.com/astral-sh/uv", stars: 52000, todayStars: 120, language: "Rust" },
  ],
  papers: [
    { title: "대규모 언어 모델의 추론 능력 확장을 위한 새로운 접근법", summary: "Chain-of-Thought를 넘어서는 새로운 추론 기법을 제안했다. 기존 방법 대비 수학 문제에서 23% 성능 향상을 달성했으며, 더 적은 토큰으로 정확한 답에 도달한다.", url: "https://arxiv.org/abs/example1", authors: "Zhang et al.", source: "ArXiv cs.CL" },
    { title: "효율적인 MoE 아키텍처: 전문가 라우팅 최적화", summary: "Mixture of Experts 모델에서 전문가 라우팅을 동적으로 최적화하는 기법을 제안했다. 학습 비용을 40% 줄이면서도 성능 저하가 없다.", url: "https://arxiv.org/abs/example2", authors: "Lee, Kim et al.", source: "ArXiv cs.LG" },
    { title: "멀티모달 모델의 시각적 할루시네이션 감소 기법", summary: "비전-언어 모델에서 이미지와 텍스트 사이의 불일치를 감지하고 교정하는 새로운 기법. POPE 벤치마크에서 SOTA를 달성했다.", url: "https://arxiv.org/abs/example3", authors: "Wang, Chen", source: "ArXiv cs.CV" },
    { title: "코드 생성 모델의 보안 취약점 자동 탐지", summary: "LLM이 생성한 코드의 보안 취약점을 자동으로 탐지하는 프레임워크. CWE Top 25 취약점의 87%를 탐지하며, 수정 제안까지 제공한다.", url: "https://arxiv.org/abs/example4", authors: "Park et al.", source: "ArXiv cs.AI" },
    { title: "양자화 없이 LLM 추론 속도를 높이는 Speculative Decoding 개선", summary: "Speculative Decoding의 새로운 변형으로, 드래프트 모델 없이도 2.5배 빠른 추론을 달성했다. 품질 저하 없이 레이턴시를 대폭 줄인다.", url: "https://arxiv.org/abs/example5", authors: "Johnson, Li", source: "ArXiv cs.CL" },
    { title: "RLHF를 대체하는 자기 보상 학습 프레임워크", summary: "인간 피드백 없이 모델 스스로 보상 신호를 생성하는 새로운 학습 방법. RLHF 대비 학습 비용이 1/10이면서 유사한 성능을 달성했다.", url: "https://arxiv.org/abs/example6", authors: "Patel, Brown et al.", source: "HuggingFace Papers" },
    { title: "에이전트 기반 소프트웨어 개발의 체계적 벤치마크", summary: "AI 코딩 에이전트의 성능을 측정하는 새로운 벤치마크 SWE-Agent를 제안했다. 실제 GitHub 이슈 해결 능력을 다각도로 평가한다.", url: "https://arxiv.org/abs/example7", authors: "Yang et al.", source: "ArXiv cs.AI" },
  ],
  generatedAt: new Date().toISOString(),
  sourceStatus: { hn: "ok", community: "ok", github: "ok", rss: "ok", papers: "ok" },
};
